### ISSUE TITLE
Entry Deny in der WarGear Region

### ISSUE THREAD

**Issue by fly4lol** [pro-crafting/wg-fight-plugin#20]
In der WarGear Region sollte eine EntryDeny Flag gesetzt werden, so dass außer Kampfleiter keiner mehr in die WarGear Region Fliegen oder laufen kann.

**Comment by fly4lol** [comment]
Die Team Region ist damit gemeint also die Region mit dem Maximal Größen des WarGears

**Comment by Postremus** [comment]
behoben mit 60d3b951
